local o = vim.o
o.number = true
o.relativenumber = true
o.tabstop = 2
o.shiftwidth = 2
o.expandtab = true
o.smartindent = true
o.wrap = false
o.termguicolors = true
o.signcolumn = "yes"
o.updatetime = 200
o.splitright = true
o.splitbelow = true
o.scrolloff = 8
o.undofile = true
o.ignorecase = true
o.smartcase = true
o.completeopt = "menuone,noselect,preview"
o.clipboard = "unnamedplus"
o.winbar = "%=%m %f"
